# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-10 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191109_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
